name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 🚀 Features
    label: 'enhancement'
  - title: 🐛 Bug Fixes
    label: 'bug'
  - title: 🛠 Internal Changes
    label: 'maintenance'
  - title: 🔍 Hunting Updates
    label: 'hunting'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes
  $CHANGES
